In [8]:
import pandas as pd
import numpy as np

# Read in the data
df = pd.read_csv('data/likes-weekly.csv')

In [13]:
# get # of model likes per week
df_model = df.loc[df['repoType'] == 'model']
df_model_likes = df_model.groupby(by=['name', 'date'], as_index=False)['likes'].sum()
df_model_likes

,name,date,likes
0,01das/test_czech_gpt2,2022-11-06T00:00:00.000Z,1
1,0x7194633/pyGPT-50M,2022-07-17T00:00:00.000Z,1
2,0xJustin/Dungeons-and-Diffusion,2022-11-06T00:00:00.000Z,37
3,0xJustin/Dungeons-and-Diffusion,2022-11-13T00:00:00.000Z,31
4,123456/Arcanegan,2021-12-26T00:00:00.000Z,1
...,...,...,...
21540,zoheb/mit-b5-finetuned-sidewalk-semantic,2022-10-09T00:00:00.000Z,1
21541,zoheb/yolos-small-balloon,2022-10-16T00:00:00.000Z,1
21542,zyayoung/cv-full-paper,2022-02-06T00:00:00.000Z,1
21543,zzxslp/RadBERT-RoBERTa-4m,2022-10-23T00:00:00.000Z,2
21544,zzxslp/RadBERT-RoBERTa-4m,2022-10-30T00:00:00.000Z,1